### @name="get all products"
GET http://localhost:8080/api/products
Accept: application/json

### @name="get products by Range"
GET http://localhost:8080/api/products?low=500&high=25000
Accept: application/json


### @name="get products by ID"
GET http://localhost:8080/api/products/3
Accept: application/json

### @name="Update Price"
PATCH http://localhost:8080/api/products/3?price=52000
Accept: application/json


### @name ="add a new product"

POST http://localhost:8080/api/products
Accept: application/json
Content-Type: application/json

{
  "name": "iPhone 16e",
  "price": 78000,
  "quantity": 100
}

