### @name="GET all Products"
GET http://localhost:8080/api/products
Accept: application/json

### @name="GET by ID"
GET http://localhost:8080/api/products/53
Accept: application/json


### @name="GET  Products by Range"
GET http://localhost:8080/api/products?low=100&high=5000
Accept: application/json


### @name="Add a Product"
POST http://localhost:8080/api/products
Accept: application/json
Content-Type: application/json

{
  "name": "",
  "price": -210000.00,
  "quantity": -99
}

### @name="Update the Product"
PUT http://localhost:8080/api/products/5
Accept: application/json
Content-Type: application/json

{
  "price": 649.45
}


