### @name ="Register User"

POST http://localhost:8080/auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "roger@cisco.com",
  "password": "secret",
  "username": "Roger",
  "roles": [ {
    "name": "ROLE_USER",
    "description": "Has basic rights"
  }]
}

### @name ="Register Admin"

POST http://localhost:8080/auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "kim@cisco.com",
  "password": "secret",
  "username": "Anna",
  "roles": [ {
    "name": "ROLE_USER",
    "description": "Has basic rights"
  },
    {
      "name": "ROLE_ADMIN",
      "description": "Admin rights"
    }]
}


### @name ="Admin Login"

POST http://localhost:8080/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "kim@cisco.com",
  "password": "secret"
}


### @name="access Protected Resource"

GET http://localhost:8080/api/products
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraW1AY2lzY28uY29tIiwiaWF0IjoxNzQ1NTcyMzY5LCJleHAiOjE3NDU2NTg3NjksInJvbGVzIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwiaXNzIjoiaHR0cHM6Ly9hdXRoLmNpc2NvLmNvbSJ9.wnSWm0fVujcmShJNUUWfNCTdQrO9xVV0xruLdXl0_1A
